spring: 
	profiles: 
		active: 			#3个减号作为分隔符
		- dev 	
---
spring: 
	profiles: dev		#开发环境
	application: 
		name: microservicecloud-config-sdl-dev 
---
spring: 
	profiles: test	#测试环境
	application: 
		name: microservicecloud-config-sdl-test 
#保存为UTF-8格式 
